### PR TITLE
Jg 128 - Fix search bug

### LINKED ISSUE #128: fix search bug
the problem  is that when we switch between tabs we dont remove search box value and the products are not being filtered by it

follow these steps:
image

### PR DESCRIPTION
**Pull request by jusgladysz**

### CODE REVIEW

File: web/src/components/pages/Products/ProductsContainer/component.tsx [hunk 1]
```diff
@@ -11,12 +11,39 @@ interface Props {
...
-
-    const optionsShoe = [{ label: '28', checked: false }, { label: '29', checked: false }, {label: '30', checked: false}, { label: '31', checked: false }, { label: '32', checked: false }, { label: '33', checked: false }, {label: '34', checked: false}, {label: '35', checked: false}, {label: '36', checked: false}, {label: '37', checked: false}, { label: '38', checked: false }, { label: '39', checked: false }, {label: '40', checked: false}, { label: '41', checked: false }, { label: '42', checked: false }, { label: '43', checked: false }, {label: '44', checked: false}, {label: '45', checked: false}, {label: '46', checked: false}, {label: '47', checked: false}, {label: '48', checked: false}];
+export const ProductsComponent = ({
+                                      productsToDisplay,
+                                      itemsOnPage,
+                                      productType,
+                                      resetFilters,
+                                  }: Props): JSX.Element => {
```
Comment (pdybowski) [inline web/src/components/pages/Products/ProductsContainer/component.tsx:22]: please format

File: web/src/components/pages/Products/ProductsContainer/component.tsx [hunk 2]
```diff
@@ -153,11 +186,12 @@ export const ProductsComponent = ({ productsToDisplay, itemsOnPage, productType
...
     }
 
-    function clearSearchByName() {
-        setNameSearch('');
-    }
+    const MultiselectCheckbox = ({
+                                     data,
+                                     setData,
+                                     onChange,
+                                 }: { data: any, setData: any, onChange: any }) => {
```
Comment (pdybowski) [inline web/src/components/pages/Products/ProductsContainer/component.tsx:193]: please format

**Review by pdybowski — CHANGES_REQUESTED** [review]
please resolve conflicts and fix comments
